#!/bin/bash -e

chmod 755 ./mvnw
./mvnw clean test

if [ $? -eq 0 ]
then
    echo "All tests pass."
    exit 0
else
    exit 1
fi
modules_arg=$(printf ",%s" "${modules[@]}");
modules_arg=${modules_arg:1};

export MAVEN_OPTS="-client
  -XX:+TieredCompilation
  -XX:TieredStopAtLevel=1
  -Xverify:none";

mvn -q -pl "$modules_arg" checkstyle:check;